### ISSUE TITLE
How to add global styles?

### ISSUE THREAD

**Issue by MuhsinFatih** [redradix/svelte-custom-element-template#2]
The description says that global styles live in styles.svelte and that we can add styles there. However every style I add there is ignored and it says "unused css selector". If I add styles with `:global()`, then that style leaks into the html document where the web-component is imported.
I created styles in a new `global.css` file and imported it in index.svelte:

```
@import url('../src/global.css');
```
And this worked as I expected (no leaks to the parent DOM).
I was expecting `styles.svelte` to do this. Am I misunderstanding its purpose?

**Comment by MonkeyAndres** [comment]
I've created the `styles.svelte` component to group all global styles for your web component. It's mainly useful for declaring CSS custom properties

So for example, I have color properties that I use in more than one component. I declare them here using `:global(:root) {}` and the magic happens when building Storybook as it injects the contents of this file to all the stories. Apart from that, there's not much happening with this file.
